Add duplicate search result API
unicef/hope-dedup-engine pull request #17
Opened 2024-05-22 09:00 UTC by sergey-misuk-valor

2024-05-23 19:57 UTC, saxix requested changes

2024-05-23 19:57 UTC, saxix commented on src/hope_dedup_engine/apps/api/models/deduplication.py
> +    first_reference_pk = models.IntegerField()
let's use CharField here. Remote systems can send anything

2024-05-23 19:57 UTC, saxix commented on src/hope_dedup_engine/apps/api/models/deduplication.py
> +    second_reference_pk = models.IntegerField()
same as above

2024-05-24 11:48 UTC, sergey-misuk-valor commented on src/hope_dedup_engine/apps/api/models/deduplication.py
> +    first_reference_pk = models.IntegerField()
Done

2024-05-24 11:48 UTC, sergey-misuk-valor commented on src/hope_dedup_engine/apps/api/models/deduplication.py
> +    second_reference_pk = models.IntegerField()
Done

2024-05-24 13:42 UTC, saxix approved these changes

2024-05-24 13:42 UTC, merged